version: "3"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hynfratech
      POSTGRES_USER: botontapwater
      POSTGRES_PASSWORD: TwoGreen1.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: >
      bash -c "
      sleep 10 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py create_rate_plans &&
      python manage.py collectstatic --noinput &&
      gunicorn hynfratech_assessment.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - /app/static
    ports:
      - "8000:8000"
    environment:
      - DATABASE=hynfratech
      - DATABASE_USERNAME=botontapwater
      - PASSWORD=TwoGreen1.
      - HOST=db
      - PORT=5432
      - DEBUG=1
      - DJANGO_SECRET_KEY='0cc8c03f8885c96774a3f1febc083c48f26e3bb0aa9e5315e5060c588d03fa64'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /app/static:/static
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
