# Generated by Django 5.0.6 on 2024-09-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Standard User', 'Standard User'), ('Guest', 'Guest')], default='Standard User', max_length=50),
        ),
    ]
