# Generated by Django 5.0.6 on 2024-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='cpu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vm',
            name='memory',
            field=models.IntegerField(default=1024),
        ),
    ]
