# Generated by Django 5.0.6 on 2024-09-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_management', '0002_vm_cpu_vm_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
