# Generated by Django 5.0.6 on 2024-09-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_management', '0006_alter_vm_memory_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
