# Generated by Django 5.0.6 on 2024-09-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_management', '0007_payment_due_date_alter_subscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='disk_size',
            field=models.IntegerField(default=1024),
        ),
    ]
