name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: hynfratech
          POSTGRES_USER: botontapwater
          POSTGRES_PASSWORD: TwoGreen1.
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U $POSTGRES_USER" --health-interval 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test

      - name: Build Docker image
        run: |
          docker build -t botontapwater/hynfratech-assessment:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push botontapwater/hynfratech-assessment:latest

  deploy:
    name: Setup Passwordless Sudo on VPS

    on:
      workflow_dispatch: # This allows the workflow to be triggered manually

    jobs:
      configure-sudo:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Install SSH client
            run: sudo apt-get install -y openssh-client

          - name: Add SSH key
            uses: webfactory/ssh-agent@v0.7.0
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - name: Configure passwordless sudo
            run: |
              ssh -o StrictHostKeyChecking=no -p 2112 lab@102.209.68.78 << 'EOF'
                'echo "lab ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${{ secrets.VPS_USERNAME }}'
                sudo whoami
